[package]
name = "hyperlane-utils"
version = "14.3.0"
readme = "README.md"
edition = "2024"
authors = ["root@ltpp.vip"]
license = "MIT"
description = """A library providing utils for hyperlane."""
keywords = ["http", "request", "response", "tcp", "redirect"]
repository = "https://github.com/hyperlane-dev/hyperlane-utils.git"
categories = ["network-programming", "web-programming"]
exclude = ["target", "Cargo.lock", "sh", ".github"]

[dependencies]
hex = "0.4.3"
log = "0.4.29"
url = "2.5.8"
snafu = "0.8.9"
ahash = "0.8.12"
redis = "1.0.2"
rinja = "0.3.5"
regex = "1.12.2"
chrono = "0.4.42"
lettre = "0.11.19"
dotenvy = "0.15.7"
futures = "0.3.31"
num_cpus = "1.17.0"
chunkify = "0.6.44"
once_cell = "1.21.3"
simd-json = "0.17.0"
twox-hash = "2.1.2"
future-fn = "0.3.10"
serde_with = "3.16.1"
serde_yaml = "0.9.33"
hot-restart = "0.6.8"
tracing-log = "0.2.0"
urlencoding = "2.1.3"
color-output = "8.2.7"
clonelicious = "2.2.12"
http-request = "8.91.74"
serde-xml-rs = "0.8.2"
lombok-macros = "1.15.7"
hyperlane-log = "3.0.3"
server-manager = "5.0.8"
file-operation = "0.8.11"
bytemuck_derive = "1.10.2"
compare_version = "1.2.9"
instrument-level = "1.0.4"
serde_urlencoded = "0.7.1"
hyperlane-macros = "10.14.11"
bin-encode-decode = "1.1.31"
recoverable-spawn = "3.9.12"
hyperlane-broadcast = "0.8.10"
std-macro-extensions = "0.26.11"
recoverable-thread-pool = "2.4.12"
hyperlane-plugin-websocket = "3.1.59"
utoipa-rapidoc = { version = "6.0.0", features = ["actix-web"] }
utoipa = { version = "5.4.0", features = ["openapi_extensions"] }
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "mysql", "postgres"] }
sea-orm = { version = "1.1.19", features = [
    "sqlx-mysql",
    "sqlx-postgres",
    "sqlx-sqlite",
    "runtime-tokio-rustls",
] }
utoipa-swagger-ui = { version = "9.0.2", features = [
    "debug-embed",
    "vendored",
    "actix-web",
] }
uuid = { version = "1.19.0", features = [
    "v1",
    "v3",
    "v4",
    "v5",
    "v6",
    "v7",
    "v8",
    "serde",
    "fast-rng",
    "macro-diagnostics",
    "arbitrary",
    "bytemuck",
    "rng-rand",
    "rng-getrandom",
    "rng",
    "md5",
    "sha1",
    "borsh",
    "zerocopy",
] }

[profile.dev]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"

[profile.release]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"
